### ISSUE TITLE
Sizes of tensors must match error

### ISSUE THREAD

**Issue by cmahnken** [laksjdjf/cgem156-ComfyUI#4]
When I have a simple background mask prompt, and a complex foreground mask prompt, and I merge them and run them through  **Load Attention couple** and into my KSampler, I get an error (see below).

My Background prompt:
> glamorous photo of Ronda, Spain on a beautiful day in the style of Annie Leibovitz, 8K, medium format, perfect photograph

My Foreground prompt:
>full body shot, fashion photograph of Britney Spears wearing (jeans :1.5),  (suit vest :1.1), standing in a relaxed pose, (pillbox hat :1.2), long pants, beautiful eyes, (perfect legs:1.5), six-pack abs, white teeth, perfect skin, detailed skin, sweaty skin, sexy, best composition, in the style of Annie Leibovitz, high fashion, luxurious, extravagant, stylish, sensual, sharp focus, 4K, opulent, elegance, stunning beauty, professional, high contrast,  highly detailed, fashion photography

My Negative prompt:
>bikini, mini-skirt, out of frame, no head, cropped person, bad composition, monochrome, bad quality, deformed, bad anatomy, ugly, extra limbs, extra fingers, (interlocked fingers), twins, 2girls, text, technicolor hair

If I cut out the **Load Attention couple** node everything works as expected (if you were expecting an unattractive result). Here's the section of my workflow that matters (there's a huge chunk that generates a random setting, photographer, etc. that I haven't included, and I've trimmed out the upscale section as well):

![Attention error](https://github.com/laksjdjf/cgem156-ComfyUI/assets/3709371/faade23d-d496-4379-b376-521048ed356b)

```ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\SD\Packages\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\SD\Packages\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\SD\Packages\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\SD\Packages\ComfyUI\nodes.py", line 1368, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "E:\SD\Packages\ComfyUI\nodes.py", line 1338, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\SD\Packages\ComfyUI\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\SD\Packages\ComfyUI\comfy\samplers.py", line 700, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\SD\Packages\ComfyUI\comfy\samplers.py", line 605, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "E:\SD\Packages\ComfyUI\comfy\samplers.py", line 544, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\comfy\k_diffusion\sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\comfy\samplers.py", line 282, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\comfy\samplers.py", line 272, in forward
    return self.apply_model(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\comfy\samplers.py", line 269, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "E:\SD\Packages\ComfyUI\comfy\samplers.py", line 249, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "E:\SD\Packages\ComfyUI\comfy\samplers.py", line 223, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "E:\SD\Packages\ComfyUI\comfy\model_base.py", line 95, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 849, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "E:\SD\Packages\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 43, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\comfy\ldm\modules\attention.py", line 632, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\SD\Packages\ComfyUI\comfy\ldm\modules\attention.py", line 459, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "E:\SD\Packages\ComfyUI\comfy\ldm\modules\diffusionmodules\util.py", line 191, in checkpoint
    return func(*inputs)
  File "E:\SD\Packages\ComfyUI\comfy\ldm\modules\attention.py", line 556, in _forward
    n = attn2_replace_patch[block_attn2](n, context_attn2, value_attn2, extra_options)
  File "E:\SD\Packages\ComfyUI\custom_nodes\attention-couple-ComfyUI\attention_couple.py", line 120, in patch
    context_cond = torch.cat([cond for cond in self.negative_positive_conds[1]], dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 1 in the list.```

**Comment by laksjdjf** [comment]
you use old [repository](https://github.com/laksjdjf/attention-couple-ComfyUI).
That bug has been fixed in this repository.
This repository simplifies the workflow but limiting some of the functionality.

**Comment by cmahnken** [comment]
Apologies. I will see about deleting that version and pulling the latest version. Thank you so much for the speedy response!
